"""Unit tests for assemble-agent-brief.py."""

from __future__ import annotations

import json
import unittest
from pathlib import Path

from tests.helpers import load_hook, sandbox_repo, write_config

aab = load_hook("assemble-agent-brief")
mg = load_hook("mg_config")


class TestTextHelpers(unittest.TestCase):
    def test_strip_header(self):
        text = "# Auto-generated by foo\nupdated: 2026-07-08\nopen: []\n"
        self.assertEqual(aab.strip_header(text), "updated: 2026-07-08\nopen: []")

    def test_tail_lines_truncates(self):
        text = "\n".join(f"line {i}" for i in range(10))
        out = aab.tail_lines(text, 5)
        self.assertIn("line 0", out)
        self.assertIn("truncated", out)
        self.assertNotIn("line 9", out)


class TestGraphScoutGate(unittest.TestCase):
    def test_scout_in_brief_when_enabled(self):
        cfg = mg.load_config(Path("/tmp"))
        cfg.update({"graph_scout_on_stop": True, "graph_scout_local": True, "ollama_context_on_start": False})
        self.assertTrue(aab.graph_scout_in_brief(cfg))

    def test_scout_excluded_in_token_first_profile(self):
        with sandbox_repo() as root:
            write_config(
                root,
                "graph_scout_on_stop: true\ngraph_scout_local: true\nollama_context_on_start: true\n",
            )
            cfg = mg.load_config(root)
        self.assertFalse(aab.graph_scout_in_brief(cfg))


class TestTopGodNodes(unittest.TestCase):
    def test_reads_graphify_out(self):
        with sandbox_repo() as root:
            graph_dir = root / "graphify-out"
            graph_dir.mkdir(parents=True)
            graph_dir.joinpath("graph.json").write_text(
                json.dumps(
                    {
                        "nodes": [
                            {"id": "a", "label": "foo.py"},
                            {"id": "b", "label": "bar.py"},
                        ],
                        "links": [
                            {"source": "a", "target": "b"},
                            {"source": "b", "target": "a"},
                        ],
                    }
                ),
                encoding="utf-8",
            )
            gods = aab.top_god_nodes(root, limit=2)
        self.assertTrue(any("foo.py" in g for g in gods))


class TestAssemble(unittest.TestCase):
    def _state_yaml(self, root: Path) -> None:
        (root / "memory" / "state.yaml").write_text(
            "# Auto-generated\nupdated: 2026-07-08\nopen:\n  - \"task\"\n",
            encoding="utf-8",
        )

    def test_assemble_writes_brief(self):
        with sandbox_repo() as root:
            write_config(root, "agent_brief: true\n")
            self._state_yaml(root)
            ok, msg = aab.assemble(root)
            brief = root / "memory" / ".agent-brief.yaml"
            self.assertTrue(ok)
            self.assertIn("assembled", msg)
            self.assertTrue(brief.is_file())
            text = brief.read_text(encoding="utf-8")
            self.assertIn("## Working memory", text)
            self.assertIn("task", text)
            self.assertIn("## Read order", text)

    def test_disabled_returns_false(self):
        with sandbox_repo() as root:
            write_config(root, "profile: minimal\n")
            self._state_yaml(root)
            ok, msg = aab.assemble(root)
        self.assertFalse(ok)
        self.assertIn("disabled", msg)

    def test_nothing_to_assemble(self):
        with sandbox_repo() as root:
            write_config(root, "agent_brief: true\n")
            ok, msg = aab.assemble(root)
        self.assertFalse(ok)
        self.assertIn("nothing", msg)

    def test_graph_scout_omitted_in_token_first_mode(self):
        with sandbox_repo() as root:
            write_config(
                root,
                "agent_brief: true\ngraph_scout_on_stop: true\ngraph_scout_local: true\n"
                "ollama_context_on_start: true\n",
            )
            self._state_yaml(root)
            (root / "memory" / ".graph-scout.yaml").write_text("risk: HIGH\n", encoding="utf-8")
            ok, _ = aab.assemble(root)
            text = (root / "memory" / ".agent-brief.yaml").read_text(encoding="utf-8")
            self.assertTrue(ok)
            self.assertNotIn("## Graph scout", text)


if __name__ == "__main__":
    unittest.main()
