#!/usr/bin/env python3
"""Merge memory/state.yaml + graph scout + god nodes into memory/.agent-brief.yaml."""

from __future__ import annotations

import importlib.util
import json
import os
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path


def _load_mg_config():
    path = Path(__file__).resolve().parent / "mg_config.py"
    spec = importlib.util.spec_from_file_location("mg_config", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


mg = _load_mg_config()


def repo_root() -> Path:
    root = os.environ.get("REPO_ROOT")
    return Path(root) if root else Path.cwd()


def strip_header(text: str) -> str:
    lines = []
    for line in text.splitlines():
        if line.startswith("# Auto-generated"):
            continue
        lines.append(line)
    return "\n".join(lines).strip()


def tail_lines(text: str, max_lines: int) -> str:
    lines = [ln for ln in text.splitlines() if ln.strip()]
    if len(lines) <= max_lines:
        return "\n".join(lines)
    return "\n".join(lines[:max_lines]) + f"\n# ... ({len(lines) - max_lines} lines truncated)"


def read_section(path: Path, max_lines: int) -> str | None:
    if not path.is_file():
        return None
    text = strip_header(path.read_text(encoding="utf-8", errors="replace"))
    if not text:
        return None
    return tail_lines(text, max_lines)


def top_god_nodes(root: Path, limit: int = 5) -> list[str]:
    graph = root / "graphify-out" / "graph.json"
    if not graph.is_file():
        return []
    try:
        g = json.loads(graph.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return []
    nodes = g.get("nodes", [])
    links = g.get("links", g.get("edges", []))
    degree: Counter = Counter()
    for e in links:
        degree[e.get("source", "")] += 1
        degree[e.get("target", "")] += 1
    node_by_id = {n["id"]: n for n in nodes}
    out: list[str] = []
    for nid, deg in degree.most_common(limit):
        label = node_by_id.get(nid, {}).get("label", nid)
        out.append(f"`{label}` ({deg} edges)")
    return out


def graph_scout_in_brief(cfg: dict) -> bool:
    if not mg.config_bool(cfg, "graph_scout_on_stop"):
        return False
    if not mg.config_bool(cfg, "graph_scout_local"):
        return False
    if mg.config_bool(cfg, "ollama_context_on_start"):
        return False
    return True


def assemble(root: Path) -> tuple[bool, str]:
    cfg = mg.load_config(root)
    if not mg.config_bool(cfg, "agent_brief"):
        return False, "agent_brief disabled"

    max_lines = int(cfg.get("agent_brief_max_lines") or 45)
    mem = root / "memory"
    mem.mkdir(parents=True, exist_ok=True)

    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    profile = cfg.get("profile", "standard")
    parts = [
        "# Auto-generated by assemble-agent-brief.py — read ONLY this file at task start.",
        f"updated: {ts}",
        f"profile: {profile}",
        "",
        "## Read order",
        "brief (this file) → main.mdc Working On → sessions/ today → archive/ on demand",
        "",
    ]

    gods = top_god_nodes(root)
    if gods:
        parts.extend(["## God nodes (graphify)", *[f"- {g}" for g in gods], ""])

    state = read_section(mem / "state.yaml", min(18, max_lines))
    scout = None
    if graph_scout_in_brief(cfg):
        scout = read_section(mem / ".graph-scout.yaml", min(20, max_lines))
    tool_brief = read_section(mem / ".tool-brief-last.txt", 10)

    if not any([state, scout, tool_brief, gods]):
        return False, "nothing to assemble"

    if state:
        parts.extend(["## Working memory", state, ""])
    if scout:
        parts.extend(["## Graph scout", scout, ""])
    if tool_brief:
        parts.extend(["## Last large tool output (summary)", tool_brief, ""])

    body = "\n".join(parts).strip() + "\n"
    body = tail_lines(body, max_lines + 10) + "\n"

    out = mem / ".agent-brief.yaml"
    out.write_text(body, encoding="utf-8")

    status = mem / ".agent-brief-status"
    status.write_text(f"ok: true\ndate: {ts}\nlines: {len(body.splitlines())}\n", encoding="utf-8")
    return True, f"assembled {len(body.splitlines())} lines"


def main() -> int:
    root = repo_root()
    if len(sys.argv) > 1 and sys.argv[1] == "--check":
        cfg = mg.load_config(root)
        out = root / "memory" / ".agent-brief.yaml"
        print(f"agent_brief: {mg.config_bool(cfg, 'agent_brief')}")
        print(f"  profile: {cfg.get('profile')}")
        print(f"  max_lines: {cfg.get('agent_brief_max_lines', 45)}")
        print(f"  file: {'ok' if out.is_file() else 'missing'}")
        return 0 if mg.config_bool(cfg, "agent_brief") else 1

    ok, msg = assemble(root)
    if not ok:
        print(msg, file=sys.stderr)
        return 1
    print(msg)
    return 0


if __name__ == "__main__":
    sys.exit(main())
