#!/usr/bin/env python3
"""Merge memory/state.yaml + memory/.graph-scout.yaml (+ optional tool brief) into one file.

Reduces agent reads from 2–3 files to 1 (~40 lines). Enable via config.yaml agent_brief: true
"""

from __future__ import annotations

import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

DEFAULT = {
    "agent_brief": True,
    "agent_brief_max_lines": 45,
}


def repo_root() -> Path:
    root = os.environ.get("REPO_ROOT")
    return Path(root) if root else Path.cwd()


def load_config(root: Path) -> dict:
    cfg = dict(DEFAULT)
    path = root / ".memory-graph" / "config.yaml"
    if not path.is_file():
        return cfg
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or ":" not in line:
            continue
        key, val = line.split(":", 1)
        key, val = key.strip(), val.strip().strip('"').strip("'")
        if key == "agent_brief":
            cfg[key] = val.lower() in ("true", "yes", "1")
        elif key == "agent_brief_max_lines":
            try:
                cfg[key] = int(val)
            except ValueError:
                pass
    return cfg


def strip_header(text: str) -> str:
    lines = []
    for line in text.splitlines():
        if line.startswith("# Auto-generated"):
            continue
        lines.append(line)
    return "\n".join(lines).strip()


def tail_lines(text: str, max_lines: int) -> str:
    lines = [ln for ln in text.splitlines() if ln.strip()]
    if len(lines) <= max_lines:
        return "\n".join(lines)
    return "\n".join(lines[:max_lines]) + f"\n# ... ({len(lines) - max_lines} lines truncated)"


def graph_scout_in_brief(root: Path, cfg: dict) -> bool:
    if not cfg.get("graph_scout_on_stop"):
        return False
    path = root / ".memory-graph" / "config.yaml"
    if not path.is_file():
        return False
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = line.strip()
        if re.match(r"^graph_scout_on_stop:\s*false", line):
            return False
        if re.match(r"^graph_scout_local:\s*true", line):
            return True
    return False


def ollama_context_mode(root: Path) -> bool:
    path = root / ".memory-graph" / "config.yaml"
    if not path.is_file():
        return False
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        if re.match(r"^ollama_context_on_start:\s*true", line.strip()):
            return True
    return False


def read_section(path: Path, max_lines: int) -> str | None:
    if not path.is_file():
        return None
    text = strip_header(path.read_text(encoding="utf-8", errors="replace"))
    if not text:
        return None
    return tail_lines(text, max_lines)


def assemble(root: Path) -> tuple[bool, str]:
    cfg = load_config(root)
    if not cfg.get("agent_brief"):
        return False, "agent_brief disabled"

    max_lines = int(cfg.get("agent_brief_max_lines") or 45)
    mem = root / "memory"
    mem.mkdir(parents=True, exist_ok=True)

    state = read_section(mem / "state.yaml", min(20, max_lines))
    scout = None
    if graph_scout_in_brief(root, cfg) and not ollama_context_mode(root):
        scout = read_section(mem / ".graph-scout.yaml", min(22, max_lines))
    tool_brief = read_section(mem / ".tool-brief-last.txt", 12)

    if not any([state, scout, tool_brief]):
        return False, "nothing to assemble"

    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    parts = [
        "# Auto-generated by assemble-agent-brief.py — read ONLY this file at task start.",
        f"updated: {ts}",
        "",
    ]

    if state:
        parts.extend(["## Working memory", state, ""])
    if scout:
        parts.extend(["## Graph scout", scout, ""])
    if tool_brief:
        parts.extend(["## Last large tool output (summary)", tool_brief, ""])

    body = "\n".join(parts).strip() + "\n"
    body = tail_lines(body, max_lines + 6) + "\n"

    out = mem / ".agent-brief.yaml"
    out.write_text(body, encoding="utf-8")

    status = mem / ".agent-brief-status"
    status.write_text(f"ok: true\ndate: {ts}\nlines: {len(body.splitlines())}\n", encoding="utf-8")
    return True, f"assembled {len(body.splitlines())} lines"


def main() -> int:
    root = repo_root()
    if len(sys.argv) > 1 and sys.argv[1] == "--check":
        cfg = load_config(root)
        out = root / "memory" / ".agent-brief.yaml"
        print(f"agent_brief: {bool(cfg.get('agent_brief'))}")
        print(f"  max_lines: {cfg.get('agent_brief_max_lines', 45)}")
        print(f"  file: {'ok' if out.is_file() else 'missing'}")
        return 0 if cfg.get("agent_brief") else 1

    ok, msg = assemble(root)
    if not ok:
        print(msg, file=sys.stderr)
        return 1
    print(msg)
    return 0


if __name__ == "__main__":
    sys.exit(main())
